# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import central_pb2 as central__pb2


class CentralStub(object):
  """O serviço concentrador / super-par
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Registro = channel.unary_unary(
        '/central.Central/Registro',
        request_serializer=central__pb2.MsgRegistro.SerializeToString,
        response_deserializer=central__pb2.MsgRetornoRegistro.FromString,
        )
    self.Busca = channel.unary_unary(
        '/central.Central/Busca',
        request_serializer=central__pb2.MsgBusca.SerializeToString,
        response_deserializer=central__pb2.MsgLocalizador.FromString,
        )
    self.Pareamento = channel.unary_unary(
        '/central.Central/Pareamento',
        request_serializer=central__pb2.MsgPareamento.SerializeToString,
        response_deserializer=central__pb2.MsgRetornoPareamento.FromString,
        )
    self.Termino = channel.unary_unary(
        '/central.Central/Termino',
        request_serializer=central__pb2.MsgVazia.SerializeToString,
        response_deserializer=central__pb2.MsgRetornoTermino.FromString,
        )


class CentralServicer(object):
  """O serviço concentrador / super-par
  """

  def Registro(self, request, context):
    """Servidor de pares se registra no concentrador
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Busca(self, request, context):
    """Cliente busca o localizador de uma chave
    quem_pediu é usado na Parte 3 para evitar loops
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pareamento(self, request, context):
    """Super-par se registra com outro super-par (Parte 3)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Termino(self, request, context):
    """Termina a execução do servidor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CentralServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Registro': grpc.unary_unary_rpc_method_handler(
          servicer.Registro,
          request_deserializer=central__pb2.MsgRegistro.FromString,
          response_serializer=central__pb2.MsgRetornoRegistro.SerializeToString,
      ),
      'Busca': grpc.unary_unary_rpc_method_handler(
          servicer.Busca,
          request_deserializer=central__pb2.MsgBusca.FromString,
          response_serializer=central__pb2.MsgLocalizador.SerializeToString,
      ),
      'Pareamento': grpc.unary_unary_rpc_method_handler(
          servicer.Pareamento,
          request_deserializer=central__pb2.MsgPareamento.FromString,
          response_serializer=central__pb2.MsgRetornoPareamento.SerializeToString,
      ),
      'Termino': grpc.unary_unary_rpc_method_handler(
          servicer.Termino,
          request_deserializer=central__pb2.MsgVazia.FromString,
          response_serializer=central__pb2.MsgRetornoTermino.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'central.Central', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
