# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: central.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='central.proto',
  package='central',
  syntax='proto3',
  serialized_pb=_b('\n\rcentral.proto\x12\x07\x63\x65ntral\"2\n\x0bMsgRegistro\x12\x13\n\x0blocalizador\x18\x01 \x01(\t\x12\x0e\n\x06\x63haves\x18\x02 \x03(\x05\"%\n\x12MsgRetornoRegistro\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\"-\n\x08MsgBusca\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\x12\n\nquem_pediu\x18\x02 \x01(\t\"%\n\x0eMsgLocalizador\x12\x13\n\x0blocalizador\x18\x01 \x01(\t\"$\n\rMsgPareamento\x12\x13\n\x0blocalizador\x18\x01 \x01(\t\"\'\n\x14MsgRetornoPareamento\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\"\n\n\x08MsgVazia\"$\n\x11MsgRetornoTermino\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\x32\xfc\x01\n\x07\x43\x65ntral\x12=\n\x08Registro\x12\x14.central.MsgRegistro\x1a\x1b.central.MsgRetornoRegistro\x12\x33\n\x05\x42usca\x12\x11.central.MsgBusca\x1a\x17.central.MsgLocalizador\x12\x43\n\nPareamento\x12\x16.central.MsgPareamento\x1a\x1d.central.MsgRetornoPareamento\x12\x38\n\x07Termino\x12\x11.central.MsgVazia\x1a\x1a.central.MsgRetornoTerminob\x06proto3')
)




_MSGREGISTRO = _descriptor.Descriptor(
  name='MsgRegistro',
  full_name='central.MsgRegistro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localizador', full_name='central.MsgRegistro.localizador', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chaves', full_name='central.MsgRegistro.chaves', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=76,
)


_MSGRETORNOREGISTRO = _descriptor.Descriptor(
  name='MsgRetornoRegistro',
  full_name='central.MsgRetornoRegistro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retorno', full_name='central.MsgRetornoRegistro.retorno', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=115,
)


_MSGBUSCA = _descriptor.Descriptor(
  name='MsgBusca',
  full_name='central.MsgBusca',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='central.MsgBusca.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quem_pediu', full_name='central.MsgBusca.quem_pediu', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=162,
)


_MSGLOCALIZADOR = _descriptor.Descriptor(
  name='MsgLocalizador',
  full_name='central.MsgLocalizador',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localizador', full_name='central.MsgLocalizador.localizador', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=201,
)


_MSGPAREAMENTO = _descriptor.Descriptor(
  name='MsgPareamento',
  full_name='central.MsgPareamento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localizador', full_name='central.MsgPareamento.localizador', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=239,
)


_MSGRETORNOPAREAMENTO = _descriptor.Descriptor(
  name='MsgRetornoPareamento',
  full_name='central.MsgRetornoPareamento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retorno', full_name='central.MsgRetornoPareamento.retorno', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=280,
)


_MSGVAZIA = _descriptor.Descriptor(
  name='MsgVazia',
  full_name='central.MsgVazia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=292,
)


_MSGRETORNOTERMINO = _descriptor.Descriptor(
  name='MsgRetornoTermino',
  full_name='central.MsgRetornoTermino',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retorno', full_name='central.MsgRetornoTermino.retorno', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=330,
)

DESCRIPTOR.message_types_by_name['MsgRegistro'] = _MSGREGISTRO
DESCRIPTOR.message_types_by_name['MsgRetornoRegistro'] = _MSGRETORNOREGISTRO
DESCRIPTOR.message_types_by_name['MsgBusca'] = _MSGBUSCA
DESCRIPTOR.message_types_by_name['MsgLocalizador'] = _MSGLOCALIZADOR
DESCRIPTOR.message_types_by_name['MsgPareamento'] = _MSGPAREAMENTO
DESCRIPTOR.message_types_by_name['MsgRetornoPareamento'] = _MSGRETORNOPAREAMENTO
DESCRIPTOR.message_types_by_name['MsgVazia'] = _MSGVAZIA
DESCRIPTOR.message_types_by_name['MsgRetornoTermino'] = _MSGRETORNOTERMINO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgRegistro = _reflection.GeneratedProtocolMessageType('MsgRegistro', (_message.Message,), dict(
  DESCRIPTOR = _MSGREGISTRO,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgRegistro)
  ))
_sym_db.RegisterMessage(MsgRegistro)

MsgRetornoRegistro = _reflection.GeneratedProtocolMessageType('MsgRetornoRegistro', (_message.Message,), dict(
  DESCRIPTOR = _MSGRETORNOREGISTRO,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgRetornoRegistro)
  ))
_sym_db.RegisterMessage(MsgRetornoRegistro)

MsgBusca = _reflection.GeneratedProtocolMessageType('MsgBusca', (_message.Message,), dict(
  DESCRIPTOR = _MSGBUSCA,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgBusca)
  ))
_sym_db.RegisterMessage(MsgBusca)

MsgLocalizador = _reflection.GeneratedProtocolMessageType('MsgLocalizador', (_message.Message,), dict(
  DESCRIPTOR = _MSGLOCALIZADOR,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgLocalizador)
  ))
_sym_db.RegisterMessage(MsgLocalizador)

MsgPareamento = _reflection.GeneratedProtocolMessageType('MsgPareamento', (_message.Message,), dict(
  DESCRIPTOR = _MSGPAREAMENTO,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgPareamento)
  ))
_sym_db.RegisterMessage(MsgPareamento)

MsgRetornoPareamento = _reflection.GeneratedProtocolMessageType('MsgRetornoPareamento', (_message.Message,), dict(
  DESCRIPTOR = _MSGRETORNOPAREAMENTO,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgRetornoPareamento)
  ))
_sym_db.RegisterMessage(MsgRetornoPareamento)

MsgVazia = _reflection.GeneratedProtocolMessageType('MsgVazia', (_message.Message,), dict(
  DESCRIPTOR = _MSGVAZIA,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgVazia)
  ))
_sym_db.RegisterMessage(MsgVazia)

MsgRetornoTermino = _reflection.GeneratedProtocolMessageType('MsgRetornoTermino', (_message.Message,), dict(
  DESCRIPTOR = _MSGRETORNOTERMINO,
  __module__ = 'central_pb2'
  # @@protoc_insertion_point(class_scope:central.MsgRetornoTermino)
  ))
_sym_db.RegisterMessage(MsgRetornoTermino)



_CENTRAL = _descriptor.ServiceDescriptor(
  name='Central',
  full_name='central.Central',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=333,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='Registro',
    full_name='central.Central.Registro',
    index=0,
    containing_service=None,
    input_type=_MSGREGISTRO,
    output_type=_MSGRETORNOREGISTRO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Busca',
    full_name='central.Central.Busca',
    index=1,
    containing_service=None,
    input_type=_MSGBUSCA,
    output_type=_MSGLOCALIZADOR,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Pareamento',
    full_name='central.Central.Pareamento',
    index=2,
    containing_service=None,
    input_type=_MSGPAREAMENTO,
    output_type=_MSGRETORNOPAREAMENTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Termino',
    full_name='central.Central.Termino',
    index=3,
    containing_service=None,
    input_type=_MSGVAZIA,
    output_type=_MSGRETORNOTERMINO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CENTRAL)

DESCRIPTOR.services_by_name['Central'] = _CENTRAL

# @@protoc_insertion_point(module_scope)
