# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pares.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pares.proto',
  package='pares',
  syntax='proto3',
  serialized_pb=_b('\n\x0bpares.proto\x12\x05pares\"+\n\x0bMsgInsercao\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\"\x1d\n\nMsgRetorno\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\"\x1c\n\x0bMsgConsulta\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"\x19\n\x08MsgValor\x12\r\n\x05valor\x18\x01 \x01(\t\"\n\n\x08MsgVazia\"%\n\x12MsgRetornoAtivacao\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\"$\n\x11MsgRetornoTermino\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\x32\xd9\x01\n\x05Pares\x12\x31\n\x08Insercao\x12\x12.pares.MsgInsercao\x1a\x11.pares.MsgRetorno\x12/\n\x08\x43onsulta\x12\x12.pares.MsgConsulta\x1a\x0f.pares.MsgValor\x12\x36\n\x08\x41tivacao\x12\x0f.pares.MsgVazia\x1a\x19.pares.MsgRetornoAtivacao\x12\x34\n\x07Termino\x12\x0f.pares.MsgVazia\x1a\x18.pares.MsgRetornoTerminob\x06proto3')
)




_MSGINSERCAO = _descriptor.Descriptor(
  name='MsgInsercao',
  full_name='pares.MsgInsercao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='pares.MsgInsercao.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='pares.MsgInsercao.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=65,
)


_MSGRETORNO = _descriptor.Descriptor(
  name='MsgRetorno',
  full_name='pares.MsgRetorno',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retorno', full_name='pares.MsgRetorno.retorno', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=96,
)


_MSGCONSULTA = _descriptor.Descriptor(
  name='MsgConsulta',
  full_name='pares.MsgConsulta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='pares.MsgConsulta.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=126,
)


_MSGVALOR = _descriptor.Descriptor(
  name='MsgValor',
  full_name='pares.MsgValor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valor', full_name='pares.MsgValor.valor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=153,
)


_MSGVAZIA = _descriptor.Descriptor(
  name='MsgVazia',
  full_name='pares.MsgVazia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=165,
)


_MSGRETORNOATIVACAO = _descriptor.Descriptor(
  name='MsgRetornoAtivacao',
  full_name='pares.MsgRetornoAtivacao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retorno', full_name='pares.MsgRetornoAtivacao.retorno', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=204,
)


_MSGRETORNOTERMINO = _descriptor.Descriptor(
  name='MsgRetornoTermino',
  full_name='pares.MsgRetornoTermino',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retorno', full_name='pares.MsgRetornoTermino.retorno', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=242,
)

DESCRIPTOR.message_types_by_name['MsgInsercao'] = _MSGINSERCAO
DESCRIPTOR.message_types_by_name['MsgRetorno'] = _MSGRETORNO
DESCRIPTOR.message_types_by_name['MsgConsulta'] = _MSGCONSULTA
DESCRIPTOR.message_types_by_name['MsgValor'] = _MSGVALOR
DESCRIPTOR.message_types_by_name['MsgVazia'] = _MSGVAZIA
DESCRIPTOR.message_types_by_name['MsgRetornoAtivacao'] = _MSGRETORNOATIVACAO
DESCRIPTOR.message_types_by_name['MsgRetornoTermino'] = _MSGRETORNOTERMINO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgInsercao = _reflection.GeneratedProtocolMessageType('MsgInsercao', (_message.Message,), dict(
  DESCRIPTOR = _MSGINSERCAO,
  __module__ = 'pares_pb2'
  # @@protoc_insertion_point(class_scope:pares.MsgInsercao)
  ))
_sym_db.RegisterMessage(MsgInsercao)

MsgRetorno = _reflection.GeneratedProtocolMessageType('MsgRetorno', (_message.Message,), dict(
  DESCRIPTOR = _MSGRETORNO,
  __module__ = 'pares_pb2'
  # @@protoc_insertion_point(class_scope:pares.MsgRetorno)
  ))
_sym_db.RegisterMessage(MsgRetorno)

MsgConsulta = _reflection.GeneratedProtocolMessageType('MsgConsulta', (_message.Message,), dict(
  DESCRIPTOR = _MSGCONSULTA,
  __module__ = 'pares_pb2'
  # @@protoc_insertion_point(class_scope:pares.MsgConsulta)
  ))
_sym_db.RegisterMessage(MsgConsulta)

MsgValor = _reflection.GeneratedProtocolMessageType('MsgValor', (_message.Message,), dict(
  DESCRIPTOR = _MSGVALOR,
  __module__ = 'pares_pb2'
  # @@protoc_insertion_point(class_scope:pares.MsgValor)
  ))
_sym_db.RegisterMessage(MsgValor)

MsgVazia = _reflection.GeneratedProtocolMessageType('MsgVazia', (_message.Message,), dict(
  DESCRIPTOR = _MSGVAZIA,
  __module__ = 'pares_pb2'
  # @@protoc_insertion_point(class_scope:pares.MsgVazia)
  ))
_sym_db.RegisterMessage(MsgVazia)

MsgRetornoAtivacao = _reflection.GeneratedProtocolMessageType('MsgRetornoAtivacao', (_message.Message,), dict(
  DESCRIPTOR = _MSGRETORNOATIVACAO,
  __module__ = 'pares_pb2'
  # @@protoc_insertion_point(class_scope:pares.MsgRetornoAtivacao)
  ))
_sym_db.RegisterMessage(MsgRetornoAtivacao)

MsgRetornoTermino = _reflection.GeneratedProtocolMessageType('MsgRetornoTermino', (_message.Message,), dict(
  DESCRIPTOR = _MSGRETORNOTERMINO,
  __module__ = 'pares_pb2'
  # @@protoc_insertion_point(class_scope:pares.MsgRetornoTermino)
  ))
_sym_db.RegisterMessage(MsgRetornoTermino)



_PARES = _descriptor.ServiceDescriptor(
  name='Pares',
  full_name='pares.Pares',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=245,
  serialized_end=462,
  methods=[
  _descriptor.MethodDescriptor(
    name='Insercao',
    full_name='pares.Pares.Insercao',
    index=0,
    containing_service=None,
    input_type=_MSGINSERCAO,
    output_type=_MSGRETORNO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Consulta',
    full_name='pares.Pares.Consulta',
    index=1,
    containing_service=None,
    input_type=_MSGCONSULTA,
    output_type=_MSGVALOR,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ativacao',
    full_name='pares.Pares.Ativacao',
    index=2,
    containing_service=None,
    input_type=_MSGVAZIA,
    output_type=_MSGRETORNOATIVACAO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Termino',
    full_name='pares.Pares.Termino',
    index=3,
    containing_service=None,
    input_type=_MSGVAZIA,
    output_type=_MSGRETORNOTERMINO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARES)

DESCRIPTOR.services_by_name['Pares'] = _PARES

# @@protoc_insertion_point(module_scope)
