# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pares_pb2 as pares__pb2


class ParesStub(object):
  """O serviço de armazenamento de pares
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Insercao = channel.unary_unary(
        '/pares.Pares/Insercao',
        request_serializer=pares__pb2.MsgInsercao.SerializeToString,
        response_deserializer=pares__pb2.MsgRetorno.FromString,
        )
    self.Consulta = channel.unary_unary(
        '/pares.Pares/Consulta',
        request_serializer=pares__pb2.MsgConsulta.SerializeToString,
        response_deserializer=pares__pb2.MsgValor.FromString,
        )
    self.Ativacao = channel.unary_unary(
        '/pares.Pares/Ativacao',
        request_serializer=pares__pb2.MsgVazia.SerializeToString,
        response_deserializer=pares__pb2.MsgRetornoAtivacao.FromString,
        )
    self.Termino = channel.unary_unary(
        '/pares.Pares/Termino',
        request_serializer=pares__pb2.MsgVazia.SerializeToString,
        response_deserializer=pares__pb2.MsgRetornoTermino.FromString,
        )


class ParesServicer(object):
  """O serviço de armazenamento de pares
  """

  def Insercao(self, request, context):
    """Insere ou atualiza um par (chave, valor)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Consulta(self, request, context):
    """Consulta o valor associado a uma chave
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ativacao(self, request, context):
    """Ativa o registro no servidor central (Parte 2)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Termino(self, request, context):
    """Termina a execução do servidor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ParesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Insercao': grpc.unary_unary_rpc_method_handler(
          servicer.Insercao,
          request_deserializer=pares__pb2.MsgInsercao.FromString,
          response_serializer=pares__pb2.MsgRetorno.SerializeToString,
      ),
      'Consulta': grpc.unary_unary_rpc_method_handler(
          servicer.Consulta,
          request_deserializer=pares__pb2.MsgConsulta.FromString,
          response_serializer=pares__pb2.MsgValor.SerializeToString,
      ),
      'Ativacao': grpc.unary_unary_rpc_method_handler(
          servicer.Ativacao,
          request_deserializer=pares__pb2.MsgVazia.FromString,
          response_serializer=pares__pb2.MsgRetornoAtivacao.SerializeToString,
      ),
      'Termino': grpc.unary_unary_rpc_method_handler(
          servicer.Termino,
          request_deserializer=pares__pb2.MsgVazia.FromString,
          response_serializer=pares__pb2.MsgRetornoTermino.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pares.Pares', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
